[mypy]
python_version = 3.12
strict = True
warn_unused_configs = True
warn_unreachable = True
show_error_codes = True
pretty = True
files = src, tests

[mypy-mongomock.*]
ignore_missing_imports = True

[mypy-google.genai.*]
ignore_missing_imports = True

[mypy-msal.*]
ignore_missing_imports = True
